# Generated by Django 5.2.5 on 2025-10-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(help_text='District code (e.g., DHK, CTG, KHL)', max_length=10, unique=True),
        ),
    ]
