# Generated by Django 5.2.5 on 2025-09-22 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
        ('organizations', '0003_syncsettings_last_sync_status_and_more'),
        ('users', '0002_user_language_preference_user_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(db_index=True, default='dept', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='users.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='users.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'Entry Level'), (2, 'Junior Level'), (3, 'Mid Level'), (4, 'Senior Level'), (5, 'Lead Level'), (6, 'Manager Level'), (7, 'Director Level'), (8, 'Executive Level')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='designation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organizations.organizations'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('code', 'organization')},
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_level',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.designation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.district'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.thana'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('billing_manager', 'Billing Manager'), ('noc_manager', 'NOC Manager'), ('support_staff', 'Support Staff'), ('reseller_admin', 'Reseller Administrator'), ('sub_reseller_admin', 'Sub-Reseller Administrator'), ('field_staff', 'Field Staff'), ('accountant', 'Accountant'), ('customer_service', 'Customer Service'), ('technical_support', 'Technical Support')], db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('code', 'organization')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'is_active'], name='departments_organiz_47d68a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent', 'is_active'], name='departments_parent__6d12cb_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code', 'organization'], name='departments_code_1d376b_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['organization', 'is_active'], name='designation_organiz_715ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['department', 'level'], name='designation_departm_69e824_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['level', 'is_active'], name='designation_level_b15fce_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='users_user_ty_beeeda_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_of_joining'], name='users_date_of_c56b82_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'user_type', 'is_active'], name='users_organiz_6dc474_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'designation'], name='users_departm_130197_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['login_id', 'is_active'], name='users_login_i_b86fee_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_email_a7cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role', 'is_active'], name='user_roles_user_id_76d171_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['created_at'], name='user_roles_created_75b2d7_idx'),
        ),
        migrations.RemoveField(
            model_name='designation',
            name='status',
        ),
    ]
