# Generated by Django 5.2.5 on 2025-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_department_options_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='code',
            field=models.CharField(db_index=True, default='designation', max_length=20),
        ),
    ]
