# Generated by Django 5.2.5 on 2025-10-12 06:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0002_alter_district_code'),
        ('organizations', '0004_alter_organizations_company_code'),
        ('users', '0004_alter_designation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role_assignment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='revoked_by',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role_level', 'display_name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_ty_beeeda_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_created_6541e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_date_of_c56b82_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_organiz_6dc474_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_departm_130197_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_login_i_b86fee_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_a7cfd1_idx',
        ),
        migrations.AddField(
            model_name='role',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization this role belongs to', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization_id', 'name')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='role',
            name='default_dashboard',
            field=models.CharField(default='dashboard', help_text='Default landing page after login', max_length=50),
        ),
        migrations.AddField(
            model_name='role',
            name='max_users',
            field=models.IntegerField(blank=True, help_text='Maximum users allowed with this role (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Primary role for this user (REQUIRED)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_assign_roles',
            field=models.BooleanField(default=False, help_text='Can this role assign roles to other users'),
        ),
        migrations.AlterField(
            model_name='role',
            name='display_name',
            field=models.CharField(help_text='Human-readable role name', max_length=150),
        ),
        migrations.AlterField(
            model_name='role',
            name='django_group',
            field=models.OneToOneField(blank=True, help_text='Auto-linked Django Group for permissions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ktl_role', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='System-managed role (cannot be deleted)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Internal role name (lowercase_with_underscores)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_level',
            field=models.PositiveIntegerField(default=100, help_text='Hierarchy level (lower = more powerful). super_admin=1, admin=10, user=100'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization_id', 'is_active'], name='roles_organiz_1c97c0_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_level'], name='roles_role_le_bf1a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization_id', 'is_active'], name='users_organiz_f36d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_id_7a277c_idx'),
        ),
        migrations.AddField(
            model_name='roleassignmenthistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignmenthistory',
            name='new_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignments', to='users.role'),
        ),
        migrations.AddField(
            model_name='roleassignmenthistory',
            name='previous_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to='users.role'),
        ),
        migrations.AddField(
            model_name='roleassignmenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.RemoveField(
            model_name='role',
            name='max_assignments',
        ),
    ]
