# Generated by Django 5.2.5 on 2025-10-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_roleassignmenthistory_alter_userrole_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], default='en', help_text='User preferred language', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Dhaka', help_text='User timezone preference', max_length=50),
        ),
    ]
