# Generated by Django 5.2.5 on 2025-10-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0002_alter_district_code'),
        ('organizations', '0004_alter_organizations_company_code'),
        ('users', '0006_user_language_preference_user_timezone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_organiz_f36d9e_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization_id'], name='users_organiz_ca9165_idx'),
        ),
    ]
