# Generated by Django 5.2.5 on 2025-08-31 07:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Kloud Technologies Ltd', max_length=255)),
                ('company_code', models.CharField(default='KTL', max_length=20, unique=True)),
                ('business_license', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_img', models.CharField(blank=True, max_length=500, null=True)),
                ('revenue_sharing_enabled', models.BooleanField(default=True)),
                ('default_reseller_share', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('default_sub_reseller_share', models.DecimalField(decimal_places=2, default=45.0, max_digits=5)),
                ('auto_approval_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
