# Generated by Django 5.2.5 on 2025-09-04 07:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Kloud Technologies Ltd', max_length=255)),
                ('company_code', models.CharField(db_index=True, default='KTL', max_length=20, unique=True)),
                ('business_license', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('dark_logo_img', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('lite_logo_img', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='organization_banners/')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='organization_og_images/')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('organization_type', models.CharField(default='Banking', max_length=50)),
                ('nid_document', models.FileField(blank=True, null=True, upload_to='organization_documents/')),
                ('payment_report', models.FileField(blank=True, null=True, upload_to='organization_documents/')),
                ('invoice_signature', models.ImageField(blank=True, null=True, upload_to='organization_signatures/')),
                ('card_logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('revenue_sharing_enabled', models.BooleanField(default=True)),
                ('default_reseller_share', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('default_sub_reseller_share', models.DecimalField(decimal_places=2, default=45.0, max_digits=5)),
                ('default_ktl_share_with_sub', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('default_reseller_share_with_sub', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('api_version', models.CharField(default='v1.0', help_text='Dynamic API version for this organization', max_length=10)),
                ('auto_approval_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_manual_grace_days', models.IntegerField(default=9)),
                ('disable_expiry', models.BooleanField(default=False)),
                ('default_grace_days', models.IntegerField(default=1)),
                ('jump_billing', models.BooleanField(default=True)),
                ('default_grace_hours', models.IntegerField(default=14)),
                ('max_inactive_days', models.IntegerField(default=3)),
                ('delete_permanent_disable_secret_from_mikrotik', models.IntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Billing Settings',
                'verbose_name_plural': 'Billing Settings',
            },
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_area_to_mikrotik', models.BooleanField(default=False)),
                ('sync_address_to_mikrotik', models.BooleanField(default=False)),
                ('sync_customer_mobile_to_mikrotik', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sync Settings',
                'verbose_name_plural': 'Sync Settings',
            },
        ),
    ]
