# Generated by Django 5.2.5 on 2025-09-01 09:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='api_version',
            field=models.CharField(default='v1.0', help_text='Dynamic API version for this organization', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='organization_banners/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='card_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='dark_logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_ktl_share_with_sub',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_reseller_share_with_sub',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='invoice_signature',
            field=models.ImageField(blank=True, null=True, upload_to='organization_signatures/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='lite_logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='nid_document',
            field=models.FileField(blank=True, null=True, upload_to='organization_documents/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='organization_og_images/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(default='Banking', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_report',
            field=models.FileField(blank=True, null=True, upload_to='organization_documents/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_manual_grace_days', models.IntegerField(default=9)),
                ('disable_expiry', models.BooleanField(default=False)),
                ('default_grace_days', models.IntegerField(default=1)),
                ('jump_billing', models.BooleanField(default=True)),
                ('default_grace_hours', models.IntegerField(default=14)),
                ('max_inactive_days', models.IntegerField(default=3)),
                ('delete_permanent_disable_secret_from_mikrotik', models.IntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Billing Settings',
                'verbose_name_plural': 'Billing Settings',
            },
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_area_to_mikrotik', models.BooleanField(default=False)),
                ('sync_address_to_mikrotik', models.BooleanField(default=False)),
                ('sync_customer_mobile_to_mikrotik', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sync Settings',
                'verbose_name_plural': 'Sync Settings',
            },
        ),
    ]
