# Generated by Django 5.2.5 on 2025-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
