# Generated by Django 5.2.5 on 2025-10-09 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_syncsettings_last_sync_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='company_code',
            field=models.CharField(db_index=True, default='KTL', help_text='Unique organization code (e.g., KTL, DHKRES01)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Organization code must contain only uppercase letters, numbers, underscores, and hyphens', regex='^[A-Z0-9_-]+$')]),
        ),
    ]
